// web/src/App.vue
<script lang="ts" setup>
import { onMounted } from "vue";
import BaseBanner from "@/layouts/BaseBanner.vue";
import Toast from "primevue/toast";
import { useToast } from "primevue/usetoast";
import { useToastStore } from "@/stores/store_toast";
import D3Clock from "@/components/D3Clock.vue";

const toast = useToast()
onMounted(() => {
    useToastStore().bind(toast)
})
</script>

<template>
    <div class="app">
        <Toast/>

        <D3Clock style="right: 100px; top: 100px"/>

        <div class="banner-container">
            <BaseBanner/>
        </div>

        <div class="view-container">
            <router-view/>
        </div>
    </div>
</template>

<style lang="scss">
.app {
    position: relative;
    width: 100%;
    height: 100%;

    .banner-container {
        position: relative;
        width: 100%;
        height: 60px;
    }

    .view-container {
        position: relative;
        width: 100%;
        height: calc(100% - 60px);
    }
}
</style>

// gh-page/src/App.tsx
import { useEffect, useRef } from "react";
import { Outlet } from "react-router-dom";
import { Toast } from "primereact/toast";
import NavigationMenu from "./components/NavigationMenu";
import { EnableDrag } from "./components/misc/EnableDrag";
import { useToastStore } from "@/scripts/misc";

export default function App() {
    const toastRef = useRef<Toast>(null)

    useEffect(() => {
        useToastStore().bind(toastRef.current)
        return () => {
            useToastStore().bind(null)
        }
    }, [])

    return (
        <div className="App custom-cursor"
             style={ {
                 position: 'relative',
                 width: '100%',
                 height: '100%',
             } }>

            <Toast ref={ toastRef }/>

            <EnableDrag
                key="test" initPos={ { right: '50px', top: '50px' } }
                innerEl={ <NavigationMenu/> }/>

            <Outlet/>
        </div>
    )
}
