// gh-page/packages/vite-vue-ts/src/main.tsx
import { createApp } from 'vue'
import App from './App.vue'
import { defineSpaApp } from "../../utils/ReactSpaConverter";

export default defineSpaApp((container) => {
    const app = createApp(App)
    return {
        mount() {
            app.mount(container)
            console.log('vue mount')

            setTimeout(() => {
                app.unmount()
            }, 10_000)
        },
        unmount() {
            app.unmount()
            console.log('vue unmount')
        }
    }
})

// gh-page/packages/vite-react-ts/src/main.tsx
import ReactDOM from 'react-dom'
import App from './App'

import { defineSpaApp } from "../../utils/ReactSpaConverter";

export default defineSpaApp((container) => {
    return {
        mount() {
            ReactDOM.render(<App/>, container)
            console.log('react mount')
        },
        unmount() {
            ReactDOM.unmountComponentAtNode(container)
            console.log('react unmount')
        }
    }
})
